### PR TITLE
[RC2]: Add README

### PR DESCRIPTION
**Pull request by CsatariGergely**
With reference to issues, prs, CoC, ToR and licenses.

### CODE REVIEW

**Comment by CsatariGergely** [comment]
[Merged based on the TSC agreement on 2024.03.05](https://wiki.anuket.io/display/HOME/2024-03-05+TSC+Agenda+and+Minutes)

**Comment by collivier** [comment]
@CsatariGergely **I would remind that TSC isn't contributing to RC2 so we can't merge PR here on behalf of TSC.** 
This patch shouldn't be merged also because the title levels are incorrect and because the links should point to the new git repo for the legal docs instead of the monolithic and former git repo https://github.com/anuket-project/anuket-specifications.

My recommendation will be to revert this and to approve a better version in a normal workflow.

**Comment by collivier** [comment]
More important this break the full RST logic and hardcode links which can be quickly false (see https://cntt.readthedocs.io/projects/rc2/en/latest/index.html)

**Comment by CsatariGergely** [comment]
- Header levels: I agree, this should be fixed. #8 will fix it 
- CoC and ToR: I do not think that we should copy these to all the sub-repos. I would keep them in the big repo.
- rst vs md: This file is _not_ part of the rendered documentation set. It just helps potential visitors to know what the repo is about.

**Pull request merged**
